# Generated by Django 4.0.7 on 2022-09-24 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_post_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='main.friend'),
        ),
    ]
