# Generated by Django 4.0.7 on 2022-10-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_message_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='friend',
        ),
        migrations.AddField(
            model_name='friend',
            name='messages',
            field=models.ManyToManyField(blank=True, to='main.message'),
        ),
    ]
